### ISSUE TITLE
Nikto might need a rebuild with the new perl

### ISSUE THREAD

**Issue by archey** [anthraxx/arch-pkgbuilds#12]
Testing Nikto version: 2.1.6-1 on arch with perl version: 5.26.0-1.

It errors out when executing the help function:
nikto -h
IO.c: loadable library and perl binaries are mismatched (got handshake key 0xdb80080, needed 0xde00080)

**Comment by anthraxx** [comment]
this is not a nikto issue but a perl one on your system. is it still happening with full system upgrade and perl version: 5.26.0-4?

**Comment by archey** [comment]
It was just a perl issues fixed with an upgrade, my bad

**Comment by anthraxx** [comment]
ok great, sry for late response forgot about this issue :yum:
