### ISSUE TITLE
[gtest] missing packaged files

### ISSUE THREAD

**Issue by acxz** [anthraxx/arch-pkgbuilds#32]
Github tracker for: https://bugs.archlinux.org/task/63793?string=gmock&project=5&type%5B0%5D=&sev%5B0%5D=&pri%5B0%5D=&due%5B0%5D=&reported%5B0%5D=&cat%5B0%5D=&status%5B0%5D=open&percent%5B0%5D=&opened=&dev=&closed=&duedatefrom=&duedateto=&changedfrom=&changedto=&openedfrom=&openedto=&closedfrom=&closedto=

**Comment by anthraxx** [comment]
fixed in latest version, thx for patch
