### ISSUE TITLE
update vim and gvim packages

### ISSUE THREAD

**Issue by prabirshrestha** [anthraxx/arch-pkgbuilds#35]
I see that vim package is quite old given that it gets updated quite frequently these days. Would it be possible to update the package to latest. I'm primarily interested in this patch which would drive adoption of lua in vim. https://github.com/vim/vim/pull/6063.

Out of curiosity how often to vim packages get updated?

**Comment by anthraxx** [comment]
os often as i find time for it :) will put a new version in the repos today

**Comment by prabirshrestha** [comment]
Awesome. Thanks for the quick turnaround. It is already available.
