### ISSUE TITLE
Issue with python-yara and python2-yara

### ISSUE THREAD

**Issue by archey** [anthraxx/arch-pkgbuilds#5]
It seems there is an issue with linking of symbols when building python-yara and python2-yara. If you import the latest python-yara and python2-yara, you will receive errors as such:

Python 2.7.12 (default, Jun 28 2016, 08:31:05) 
[GCC 6.1.1 20160602] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/python2.7/site-packages/yara.so: undefined symbol: yr_finalize

Python 3.5.2 (default, Jun 28 2016, 08:46:01) 
[GCC 6.1.1 20160602] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import yara
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /usr/lib/python3.5/site-packages/yara.cpython-35m-x86_64-linux-gnu.so: undefined symbol: yr_finalize
>>> quit()

There have been a few issues about it on the yara-python github:
https://github.com/VirusTotal/yara-python/issues/7

**Comment by anthraxx** [comment]
82f7fb7615c28628486552b19a4bbb3dbd7d3f67
